"""Stage 4 - figures and a markdown summary from whichever stages have been run.

Reads results/{diagnostic,detector,restoration,cue_sweep}/ and writes
results/figures/*.png and results/SUMMARY.md.
"""

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import _bootstrap  # noqa: F401
from bolero.config import RESULTS_DIR
from bolero.plotting import (
    DIVERGING, INK_PRIMARY, SEQUENTIAL, apply_style, diverging_norm, strip_axes,
)

METHOD_ORDER = ["oracle_classical", "detector_classical"]


def annotate(ax, values: np.ndarray, fmt: str, cmap, norm) -> None:
    for (i, j), v in np.ndenumerate(values):
        if np.isnan(v):
            continue
        r, g, b, _ = cmap(norm(v))
        dark_cell = 0.299 * r + 0.587 * g + 0.114 * b < 0.5
        ax.text(j, i, format(v, fmt), ha="center", va="center", fontsize=8,
                color="white" if dark_cell else INK_PRIMARY)


def heatmap(values: pd.DataFrame, title: str, cbar_label: str, path: Path, diverging: bool, fmt: str) -> None:
    arr = values.to_numpy(dtype=float)
    cmap = DIVERGING if diverging else SEQUENTIAL
    norm = diverging_norm(np.nan_to_num(arr)) if diverging else plt.Normalize(0, max(1e-6, np.nanmax(arr)))
    fig, ax = plt.subplots(figsize=(1.1 + 0.9 * arr.shape[1], 0.9 + 0.36 * arr.shape[0]))
    im = ax.imshow(arr, cmap=cmap, norm=norm, aspect="auto")
    ax.set_xticks(range(arr.shape[1]), [str(c) for c in values.columns], rotation=35, ha="right")
    ax.set_yticks(range(arr.shape[0]), [str(i) for i in values.index])
    ax.grid(False)
    strip_axes(ax, keep=())
    annotate(ax, arr, fmt, cmap, norm)
    cbar = fig.colorbar(im, ax=ax, fraction=0.04, pad=0.02)
    cbar.set_label(cbar_label)
    cbar.outline.set_visible(False)
    ax.set_title(title)
    fig.savefig(path)
    plt.close(fig)


def md_table(df: pd.DataFrame, floatfmt: str = ".3f") -> str:
    def cell(v):
        return format(v, floatfmt) if isinstance(v, (float, np.floating)) else str(v)
    lines = ["| " + " | ".join(map(str, df.columns)) + " |", "|" + "---|" * len(df.columns)]
    lines += ["| " + " | ".join(cell(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=RESULTS_DIR)
    args = parser.parse_args()
    apply_style()
    figures = args.results / "figures"
    figures.mkdir(parents=True, exist_ok=True)
    report = ["# Results summary", "", "Generated by `scripts/analyze.py`.", ""]

    # ---- Stage 1: diagnostic ----
    diag = args.results / "diagnostic"
    if (diag / "summary.csv").exists():
        head = json.loads((diag / "headline.json").read_text())
        summary = pd.read_csv(diag / "summary.csv")
        drop = summary.pivot(index="perturbation", columns="level", values="delta_pp")
        drop = drop.loc[drop.mean(axis=1).sort_values().index]
        drop.columns = [f"level {c}" for c in drop.columns]
        heatmap(drop, "Accuracy change under perturbation", "Δ top-1 accuracy vs clean (pp)",
                figures / "diagnostic_accuracy_change.png", diverging=True, fmt=".1f")
        report += [
            "## Stage 1: diagnostic sweep", "",
            f"- {head['records']:,} records from {head['images']:,} images, "
            f"{head['perturbations']} perturbations x {head['levels']} severities",
            f"- Clean accuracy {head['clean_accuracy']:.1%}; perturbed accuracy {head['perturbed_accuracy']:.1%}",
            f"- Prediction changed in {head['prediction_changed_rate']:.2%} of records; "
            f"{head['correct_to_wrong']:,} correct->wrong, {head['wrong_to_correct']:,} wrong->correct",
            "", "![](figures/diagnostic_accuracy_change.png)", "",
            md_table(summary[["perturbation", "level", "acc_pert", "delta_pp", "changed_rate",
                              "correct_to_wrong", "wrong_to_correct", "psnr", "ssim"]]),
            "",
        ]

    # ---- Stage 2: detector ----
    det = args.results / "detector"
    if (det / "eval_predictions.csv").exists():
        head = json.loads((det / "headline.json").read_text())
        evals = pd.read_csv(det / "eval_predictions.csv")
        order = ["clean"] + [p for p in evals["true"].unique() if p != "clean"]
        confusion = pd.crosstab(evals["true"], evals["predicted"], normalize="index")
        confusion = confusion.reindex(index=order, columns=order, fill_value=0.0)
        heatmap(confusion, "Detector confusion (val)", "fraction of true class",
                figures / "detector_confusion.png", diverging=False, fmt=".2f")
        report += [
            "## Stage 2: perturbation detector", "",
            f"- Top-1 accuracy {head['top1_accuracy']:.1%} over {head['val_samples']:,} val samples",
            f"- Clean false-alarm rate {head['clean_false_alarm_rate']:.1%} at threshold {head['threshold']}",
            f"- Perturbed inputs routed to restoration: {head['perturbed_detected_rate']:.1%}",
            "", "![](figures/detector_confusion.png)", "",
        ]

    # ---- Stage 3: restoration ----
    rest = args.results / "restoration"
    if (rest / "summary.csv").exists():
        summary = pd.read_csv(rest / "summary.csv")
        methods = [m for m in METHOD_ORDER if m in set(summary["method"])]
        methods += sorted(m for m in summary["method"].unique() if m not in methods and m != "none")
        gain = (summary[summary["method"] != "none"]
                .groupby(["perturbation", "method"])["delta_pp"].mean()
                .unstack("method").reindex(columns=methods))
        rows = ["clean"] + [p for p in gain.index if p != "clean"]
        gain = gain.reindex(rows)
        heatmap(gain, "Accuracy change from restoration (mean over severities)",
                "Δ top-1 accuracy vs perturbed input (pp)",
                figures / "restoration_gain.png", diverging=True, fmt=".1f")
        overall = (summary[summary["perturbation"] != "clean"]
                   .groupby("method")[["acc_perturbed", "acc_restored", "delta_pp", "recovery_rate",
                                        "wrong_to_correct", "correct_to_wrong", "restore_ms"]]
                   .agg({"acc_perturbed": "mean", "acc_restored": "mean", "delta_pp": "mean",
                         "recovery_rate": "mean", "wrong_to_correct": "sum",
                         "correct_to_wrong": "sum", "restore_ms": "mean"})
                   .reset_index())
        on_clean = summary[summary["perturbation"] == "clean"][["method", "delta_pp", "changed_rate"]]
        report += [
            "## Stage 3: restoration", "",
            "Row `clean` shows what each method does to unperturbed inputs (the cost of a false alarm).",
            "", "![](figures/restoration_gain.png)", "",
            "Across all perturbations and severities:", "", md_table(overall), "",
            "On clean inputs:", "", md_table(on_clean.rename(columns={"delta_pp": "delta_pp_vs_clean"})), "",
        ]

    # ---- Cue sweep ----
    sweep = args.results / "cue_sweep"
    if (sweep / "summary.csv").exists():
        summary = pd.read_csv(sweep / "summary.csv")
        fig, ax = plt.subplots(figsize=(7.5, 4.2))
        for cue, g in summary.groupby("cue", sort=False):
            ax.plot(g["strength"], 100 * g["changed_rate"], marker="o", label=cue.replace("_", " "))
        ax.set_xlabel("cue strength")
        ax.set_ylabel("predictions changed vs clean (%)")
        ax.set_title("Clean-image stability of each contextual cue")
        ax.legend(loc="upper left")
        strip_axes(ax)
        fig.savefig(figures / "cue_sweep.png")
        plt.close(fig)
        pivot = summary.pivot(index="strength", columns="cue", values="changed_rate").reset_index()
        report += ["## Cue strength sweep (clean images)", "", "![](figures/cue_sweep.png)", "",
                   "Fraction of predictions changed vs. the clean image:", "", md_table(pivot), ""]

    (args.results / "SUMMARY.md").write_text("\n".join(report))
    print(f"Wrote {args.results / 'SUMMARY.md'} and {figures}/")


if __name__ == "__main__":
    main()
